export const foods = [
    {
        id_produto: 1,
        nome: "Hambúrguer Clássico",
        descricao: "Delicioso hambúrguer com carne suculenta e queijo.",
        icone: 'https://receitasdepesos.com.br/wp-content/uploads/2023/09/hamburguer-com-creme-de-cheddar-e-pao-de-brioche.jpg.webp',
        vl_produto: "15.00",
        ind_ativo: "S",
    },
    {
        id_produto: 2,
        nome: "X-Burguer",
        descricao: "Hambúrguer com queijo, bacon e cebola.",
        icone: "https://cloudfront-us-east-1.images.arcpublishing.com/estadao/GUOGMQ4FRJIUPAWMYLE4WNA3SY.jpg",
        vl_produto: "18.00",
        ind_ativo: "S",
    },
    {
        id_produto: 3,
        nome: "X-Burguer Duplo",
        descricao: "Duplo hambúrguer com queijo, bacon, cebola e alface.",
        icone: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSXU4AJQm56xFuh5o01C_3-2rV9cBmEHyq4A&s",
        vl_produto: "24.00",
        ind_ativo: "S",
    },
    {
        id_produto: 4,
        nome: "Burguer de Frango",
        descricao: "Hambúrguer de frango grelhado com maionese e alface.",
        icone: "https://assets.unileversolutions.com/recipes-v2/240147.jpg",
        vl_produto: "17.00",
        ind_ativo: "S",
    },
    {
        id_produto: 5,
        nome: "Burguer Vegetariano",
        descricao: "Hambúrguer vegetariano com abacate e tomate.",
        icone: "https://www.iglo.pt/-/media/project/bluesteel/iglo-pt/receitas/2020/receitas-vegetarianas/hamburguer-vegetariano-abacate-tomate-confitado.png?w=720&h=426&as=0&fit=1&hash=4F080690E45CBD45AFAB7666CD434F15",
        vl_produto: "16.00",
        ind_ativo: "S",
    },
];

export const pizzas = [
    {
        id_produto: 1,
        nome: "Pizza Margherita",
        descricao: "Pizza clássica com molho de tomate, mozzarella e manjericão.",
        icone: "https://s2-receitas.glbimg.com/wb7DIMyCpEyV07sTAtcDWD8HQjw=/0x0:1200x675/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2024/h/r/EfCbvqTbeDRAD3Lzc5xA/pizza-margherita.jpg",
        vl_produto: "30.00",
        ind_ativo: "S",
    },
    {
        id_produto: 2,
        nome: "Pizza Quatro Queijos",
        descricao: "Pizza com quatro tipos de queijo.",
        icone: "https://jeffersondealmeida.com.br/wp-content/uploads/2022/07/link-12.png",
        vl_produto: "40.00",
        ind_ativo: "S",
    },
    {
        id_produto: 3,
        nome: "Pizza Strogonoff de Carne",
        descricao: "Pizza deliciosa com carne strogonoff e queijo.",
        icone: "https://painacozinha.com/wp-content/uploads/238.Pizza-de-Estrogonofe.webp",
        vl_produto: "45.00",
        ind_ativo: "S",
    },
    {
        id_produto: 4,
        nome: "Pizza Portuguesa",
        descricao: "Pizza com presunto, ovo, cebola e azeitonas.",
        icone: "https://www.ogastronomo.com.br/upload/389528334-curiosidades-sobre-a-pizza-portuguesa.jpg",
        vl_produto: "35.00",
        ind_ativo: "S",
    },
    {
        id_produto: 5,
        nome: "Pizza Calabresa",
        descricao: "Pizza com calabresa, cebola e azeitonas.",
        icone: "https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3277542:1663012513/Pizza-de-calabresa.jpg?f=default&$p$f=00df3e9",
        vl_produto: "32.00",
        ind_ativo: "S",
    },
];

export const bebidas = [
    {
        id_produto: 1,
        nome: "Coca-Cola Lata",
        descricao: "Coca-Cola em lata 350ml.",
        icone: "https://andinacocacola.vtexassets.com/arquivos/ids/158244/Coca-Cola-Original-350ml-Lata---110130_COCA_PAI.png?v=638628901095270000",
        vl_produto: "5.00",
        ind_ativo: "S",
    },
    {
        id_produto: 2,
        nome: "Guaraná Antarctica",
        descricao: "Refrigerante Guaraná Antarctica 350ml.",
        icone: "https://app.cardapiodigital.net/thewrestaurante/1814-large_default/guarana-lata.jpg",
        vl_produto: "5.00",
        ind_ativo: "S",
    },
    {
        id_produto: 3,
        nome: "Água Mineral",
        descricao: "Água mineral em garrafa 500ml.",
        icone: "https://hiperideal.vtexassets.com/arquivos/ids/197243-800-450?v=637823636558600000&width=800&height=450&aspect=true",
        vl_produto: "3.00",
        ind_ativo: "S",
    },
    {
        id_produto: 4,
        nome: "Suco Natural de Laranja",
        descricao: "Suco natural de laranja 300ml.",
        icone: "https://www.sabornamesa.com.br/media/k2/items/cache/b018fd5ec8f1b90a1c8015900c2c2630_L.jpg",
        vl_produto: "6.00",
        ind_ativo: "S",
    },
    {
        id_produto: 5,
        nome: "Suco Natural de Abacaxi",
        descricao: "Suco natural de abacaxi 300ml.",
        icone: "https://pesqueiroestancia.com.br/wp-content/uploads/2020/12/Receita-de-Suco-de-abacaxi-Tudo-Gostoso.jpg",
        vl_produto: "6.00",
        ind_ativo: "S",
    },
    {
        id_produto: 6,
        nome: "Suco Natural de Manga",
        descricao: "Suco natural de manga 300ml.",
        icone: "https://cdn.abrahao.com.br/base/dca/b23/5bb/suco-natural-manga.jpg",
        vl_produto: "6.00",
        ind_ativo: "S",
    },
];

